CREATE OR REPLACE FUNCTION faturamento_total()
RETURNS NUMERIC AS
$$
SELECT SUM (valor) 
FROM pagamento;
$$
LANGUAGE SQL;

SELECT * FROM faturamento_total();

CREATE OR REPLACE FUNCTION faturamento_mensal(INTEGER, INTEGER)
RETURNS NUMERIC AS
$$
SELECT COALESCE(SUM(valor),0)
FROM pagamento 
WHERE EXTRACT(YEAR FROM datapagamento) = $1 AND EXTRACT(MONTH FROM datapagamento) = $2;
$$
LANGUAGE SQL;

SELECT * FROM faturamento_mensal(2026, 4); -- UNICO MES E ANO EM QUE HOUVERAM PAGAMENTOS REALIZADOS ATÉ DADO O MOMENTO!
